export default {
  tutorialSidebar: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        {
          type: "doc",
          id: "intro",
        },
      ],
    },
    {
      type: "category",
      label: "Architecture",
      items: [
        {
          type: "doc",
          id: "architecture/system-context",
        },
        {
          type: "doc",
          id: "architecture/container-architecture",
        },
        {
          type: "doc",
          id: "architecture/component-architecture",
        },
        {
          type: "doc",
          id: "architecture/data-flow",
        },
        {
          type: "doc",
          id: "architecture/architectural-patterns",
        },
      ],
    },
    {
      type: "category",
      label: "Workflows",
      items: [
        {
          type: "doc",
          id: "workflows/portfolio-calculation",
        },
        {
          type: "doc",
          id: "workflows/activity-import",
        },
        {
          type: "doc",
          id: "workflows/market-data-sync",
        },
        {
          type: "doc",
          id: "workflows/authentication",
        },
        {
          type: "doc",
          id: "workflows/addon-lifecycle",
        },
      ],
    },
    {
      type: "category",
      label: "Development",
      items: [
        {
          type: "doc",
          id: "development/overview",
        },
        {
          type: "category",
          label: "Activities",
          items: [
            {
              type: "autogenerated",
              dirName: "development/activities",
            },
          ],
        },
        {
          type: "category",
          label: "Goals",
          items: [
            {
              type: "autogenerated",
              dirName: "development/goals",
            },
          ],
        },
        {
          type: "category",
          label: "VN Market Integration",
          items: [
            "development/vn-market/vn-assets-synchronization",
            {
              type: "autogenerated",
              dirName: "development/vn-market",
            },
          ],
        },
        {
          type: "category",
          label: "UI & Design",
          items: [
            {
              type: "doc",
              id: "development/ui-revamp-implementation",
            },
          ],
        },
        {
          type: "category",
          label: "Internationalization",
          items: [
            {
              type: "doc",
              id: "development/i18n",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "API Reference",
      items: [
        {
          type: "doc",
          id: "api/overview",
        },
      ],
    },

  ],
};
